### ISSUE TITLE
'type' is a weak label

### ISSUE THREAD

**Issue by tristanwietsma** [tristanwietsma/tabler#4]
maybe change this to something else....

**Comment by mholt** [comment]
Keep in mind that it's conventional for tag labels to match the package name: https://groups.google.com/d/msg/golang-nuts/4Lf1ONrkSdo/0XOIP7UhUwsJ (not sure why, but some of the messages got deleted, but they're still quoted in some replies) - either way, though, most other words would be better than "type".

**Comment by tristanwietsma** [comment]
yeah, i'm leaning towards namespacing. thanks for the link.

**Comment by tristanwietsma** [comment]
New format:

``` go
tabler:"columnType=uuid&primary=true"
```
